### ISSUE TITLE
Add API documentation

### ISSUE THREAD

**Issue by codingjoe** [Findus23/pyLanguagetool#39]
Hi,

I noticed that only the CLI portion of this package is documented. I my humble opinion the Python API deserves some documentation too, especially since people are looking for an alternative to pyenchant.

Mind if I give it a go? I am fairly familiar with Sphinx and readthedocs setup as well as writing documentation.

I might throw in a little Sphinx extension, while I am at it ;)

Best
-Joe

**Comment by Findus23** [comment]
Hm, I'm not sure how usefull an API doc is. `api.py` is a fairly trivial mapping from the JSON API (that is documented in https://languagetool.org/http-api/swagger-ui/#/default) to function arguments. 
I doubt anyone would use this as a dependency instead of writing the 30 lines themselves.

But if you are in the mood to contribute I won't stop you :slightly_smiling_face:

**Comment by Findus23** [comment]
0.7.0 with those and more changes has been released and there is now also a changelog page:
https://pylanguagetool.lw1.at/changelog.html
